version: "3.5"
services:
  database:
    image: mysql:5.7.28
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
    - ../.data/var/lib/mysql:/var/lib/mysql
    ports: [33060:3306]
