stages:
  - initialise
  - package
  - release
  - publish

ui dependencies:
  stage: initialise
  image: usvc/ci:js-dependencies
  only: ["master"]
  cache:
    key: ${CI_COMMIT_REF_NAME}_ui_dependencies
    paths: ["./node_modules"]
  artifacts:
    expire_in: 1 week
    paths: ["./node_modules"]
  variables:
    PRODUCTION: 'false'
  script: ["entrypoint"]

api dependencies:
  stage: initialise
  image: usvc/ci:go-dependencies
  cache:
    key: ${CI_COMMIT_REF_NAME}_api_dependencies
    paths: ["./vendor"]
  artifacts:
    expire_in: 1 week
    paths: ["./vendor"]
  script: ["entrypoint"]


dockerize api:
  stage: package
  only: ["master"]
  services: ["docker:19.03.1-dind"]
  image: usvc/ci:docker-build
  artifacts:
    paths: ["./docker_images/*"]
  cache:
    untracked: true
    policy: pull-push
    key: ${CI_COMMIT_REF_NAME}_dockerize_api
    paths:
      - ./docker_images
  variables:
    DOCKERFILE_PATH: ./deploy/api/Dockerfile
    DOCKER_IMAGE_URL: zephinzer/codeprac-api
    OUTPUT_DIRECTORY: ./docker_images
    TEST_SPEC_PATH: ./deploy/api/Dockerfile.yaml
  script: ["entrypoint"]

dockerize ui:
  stage: package
  only: ["master"]
  services: ["docker:19.03.1-dind"]
  image: usvc/ci:docker-build
  artifacts:
    paths: ["./docker_images/*"]
  cache:
    untracked: true
    policy: pull-push
    key: ${CI_COMMIT_REF_NAME}_dockerize_ui
    paths:
      - ./docker_images
  variables:
    DOCKERFILE_PATH: ./deploy/ui/Dockerfile
    DOCKER_IMAGE_URL: zephinzer/codeprac-ui
    OUTPUT_DIRECTORY: ./docker_images
    TEST_SPEC_PATH: ./deploy/ui/Dockerfile.yaml
  script: ["entrypoint"]

version bump:
  stage: release
  only: ["master"]
  image: usvc/ci:version-bump-gitlab
  script: ["entrypoint"]

pages:
  stage: publish
  image: node:lts-alpine
  dependencies: [ui dependencies]
  only: ["master"]
  artifacts:
    paths: [public]
  variables:
    REACT_APP_API_URL_BASE: ${REACT_APP_API_URL_BASE}
  script:
    - npm run build
    # these are for gitlab pages, see https://gitlab.com/gitlab-org/gitlab-foss/-/issues/40686
    - rm -rf ./public
    - mv build public
