stages:
  - initialise
  - publish
image: node:lts-alpine

install dependencies:
  stage: initialise
  script:
    - npm ci

pages:
  stage: publish
  dependencies:
    - install dependencies
  artifacts:
    paths:
      - build
  script:
    - npm build
