stages:
  - initialise
  - publish
image: node:lts-alpine

install dependencies:
  stage: initialise
  artifacts:
    expire_in: 1 week
    paths:
      - node_modules
  script:
    - npm ci

pages:
  stage: publish
  dependencies:
    - install dependencies
  artifacts:
    paths:
      - build
  script:
    - npm run build
