version: "3.5"
networks:
  codeprac:
    name: codeprac
services:
  database:
    image: mysql:5.7.28
    environment: &databaseCredentials
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      MYSQL_DATABASE: mysql_database
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes: []
    # - .data/var/lib/mysql:/var/lib/mysql
    networks: [codeprac]
    ports: ["3307:3306"]
  api:
    build:
      context: ../
      dockerfile: ./deploy/api/Dockerfile
    image: zephinzer/codeprac-api:latest
    entrypoint: ["/entrypoint", "start"]
    environment:
      GITHUB_CLIENT_ID: __github_client_id__
      GITHUB_CLIENT_SECRET: __github_client_secret__
      GITHUB_REDIRECT_URI: __github_redirect_uri__
      LOGIN_URL: __login_url__
      SERVER_ADDR: '0.0.0.0'
      SERVERPORT: '30000'
    networks: [codeprac]
    ports: ["30001:30000"]
  ui:
    build:
      context: ../
      dockerfile: ./deploy/ui/Dockerfile
    image: zephinzer/codeprac-ui:latest
    networks: [codeprac]
    ports: ["3001:3000"]
